# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

  platform :android do

  desc "Upload metadata to Google Play Store"
  lane :upload_metadata do
    upload_to_play_store(
      skip_upload_changelogs: true
    )
  end

  desc "Deploy a new version to the beta track on the Google Play"
  lane :beta do
    gradle(
      task: "bundle",
      flavor: "Full",
      build_type: "Release",
      print_command: true
    )
    upload_to_play_store(
      track: "beta",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Generate screenshots of locales for which metadata exists"
  lane :generate_screenshots do
    locales = sh("LOCALES=$(find metadata/android -mindepth 1 -maxdepth 1 -type d -exec basename {}  \\; | sort); printf ${LOCALES\/\/$'\\n'\/','}")
    gradle(
      task: "assemble",
      flavor: "Full",
      build_type: "Debug",
      print_command: true
    )
    gradle(
      task: "assemble",
      flavor: "Full",
      build_type: "DebugAndroidTest",
      print_command: true
    )
    capture_android_screenshots(
      locales: locales
    )
  end

end
