# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

  platform :android do
  desc "Deploy a new beta version to the Google Play"
  lane :beta do
    gradle(task: "clean bundleRelease")
    mapping_path = File.absolute_path "../app/build/outputs/mapping/release/mapping.txt"
    upload_to_play_store(
      track: 'beta',
      mapping: mapping_path,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new production version to the Google Play"
  lane :production do
    gradle(task: "clean bundleRelease")
    mapping_path = File.absolute_path "../app/build/outputs/mapping/release/mapping.txt"
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      mapping: mapping_path,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
