name: Cast Receiver
on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths:
      - ".github/workflows/cast-receiver.yaml" # trigger on workflow changes as well
      - "cast-receiver/**"
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
    paths:
      - ".github/workflows/cast-receiver.yaml" # trigger on workflow changes as well
      - "cast-receiver/**"

jobs:
  build:
    name: Parcel Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: yarn && yarn build
        working-directory: ./cast-receiver

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: yarn && yarn test:single
        working-directory: ./cast-receiver
      - uses: codecov/codecov-action@v1
        with:
          flags: cast_receiver

  deploy:
    name: Deploy
    if: github.repository == 'ashutoshgngwr/noice' && github.event_name == 'push'
    needs: [build, unit-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: yarn && yarn add -D netlify-cli && yarn build
        working-directory: ./cast-receiver
      - name: Deploy as dev build
        run: yarn netlify deploy -p --dir=./dist
        working-directory: ./cast-receiver
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
      - name: Deploy as production build
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: yarn netlify deploy -p --dir=./dist
        working-directory: ./cast-receiver
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
